### ISSUE TITLE
Missing source files 

### ISSUE THREAD

**Issue by PetrGlad** [salaboy/lego-wedo4j#1]
No sources for classes com.salaboy.legowedo4j.api.Motors and com.salaboy.legowedo4j.impl.WeDo

**Comment by salaboy** [comment]
sorry I missed this issue creation and it was about a year ago. Sorry again!

**Comment by PetrGlad** [comment]
I made a fork with reduced dependencies to play with. It's based on code that supports only single device from previous working sources. Anyway I had only one controller and motor so could not test the rest.
